name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: version
      run: ./ver-manage.bash
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cicd-test:$(cat version.txt)
    - name: Login into Dockerhub
      run: docker login -u mengkheang -p dckr_pat_Usci7rplX5muCuw6Kz6es9ujFyQ
    - name: push to registry
      run: docker images 
    
